name: Spyros Simotas, PhD Candidate & Praxis Fellow, University of Virginia
description: Freelance Digital Designer & Front-end Developer, Belfast
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty

#website: http://mckvr.com

# baseurl: //mckvr.com

author: Spyros Simotas

# logo: /images/dist/android-chrome-384x384.png

# Social
social:
  name: Spyros Simotas
  links:
    - https://twitter.com/ss4ws
    - https://github.com/ss4ws
  twitter:
    username: ss4ws
    url: https://twitter.com/
  github:
    username: ss4ws
    url: https://github.com/
  email: ss4ws@virginia.edu

#directores
imageurl: /images/dist/
videourl: /videos/

# Global classes
link_classes: link underline-hover blue hover-blue active-black
code_classes: bg-washed-blue pa1
post_heading_classes: f3 lh-title
paragraph_classes: f6 f5-ns

# Gems
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

# Settings for archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: 'category-archive'
  permalinks:
    category: '/category/:name/'
  category_archive:
    type: liquid

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Custom configs
#daily_rate: £300
#hourly_rate: £40

# Navigation
navigation:
  - title: Blog
    url: /blog/
  - title: Vitæ
    url: /vita/
  - title: Teaching ePortfolio
    url: /ePortfolio/

